# inference.py

import argparse
import os

# =================================================================
# 0. Dynamic path resolution and low-level environment variable configuration
# =================================================================
# 1. Get the absolute path of the directory containing this script (src/stage2_final)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# 2. Locate the project root directory (go up two levels)
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "../../"))

# 3. Environment variable configuration (must be set before importing torch/vllm)
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
os.environ["NCCL_P2P_DISABLE"] = "1"
os.environ["NCCL_IB_DISABLE"] = "1"
os.environ["VLLM_WORKER_MULTIPROC_METHOD"] = "spawn"
os.environ["VLLM_USE_MODELSCOPE"] = "False"
# Put the cache directory under the .cache folder in the project root to avoid polluting the global cache
os.environ["MODELSCOPE_CACHE"] = os.path.join(PROJECT_ROOT, ".cache")

# =================================================================
# 1. Unified library imports
# =================================================================
import gc
import json
import re
from typing import Tuple

import cv2
import numpy as np
import pandas as pd
import pycocotools.mask as mask_utils
import torch
import torch.nn.functional as F

# Custom library and model imports
from forensics_sam import ForensicsSAM
from PIL import Image
from segment_anything import sam_model_registry
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm
from transformers import AutoProcessor
from vllm import LLM, SamplingParams


# =================================================================
# 2. Global unified configuration (dynamically assembled from project root)
# =================================================================
class CFG:
    # --- Stage 1: SAM model configuration ---
    # Points to models/adapters/stage2_final/weight
    WEIGHT_DIR = os.path.join(
        PROJECT_ROOT, "models", "adapters", "stage2_final", "weight"
    )
    SAM_TYPE = "vit_h"
    # Points to models/sam_vit_h_4b8939.pth
    SAM_CHECKPOINT = os.path.join(PROJECT_ROOT, "models", "sam_vit_h_4b8939.pth")
    IMAGE_SIZE = 1024
    BATCH_SIZE = 1
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    FULL_MODEL_WEIGHT = 0.20
    MANUAL_THRESHOLD = 0.44

    # --- Stage 2: LLM model configuration ---
    # Dynamically points to the new folder generated by connect-lora.py
    LLM_MODEL_PATH = os.path.join(PROJECT_ROOT, "models", "final_full_model")
    MAX_TOKENS = 1024 * 8
    TEMPERATURE = 0.2
    MAX_MODEL_LEN = 1024 * 16
    TENSOR_PARALLEL = 1

    # Tunable probability interval (threshold that triggers LLM judgment)
    PROB_LOWER = 0.48
    PROB_UPPER = 0.55

    # Prompts
    PROMPT_CLASSIFY = "Determine whether this image has been tampered with. If it is a tampered/forged image, output only the word 'FAKE'; if it is a real, untampered image, output only the word 'REAL'. Do not output any other characters or explanations."
    PROMPT_REAL = "This is a real image (not tampered). Analyze this image and describe the target content in the image in detail:"
    PROMPT_FAKE = "This is a tampered (forged) image. Analyze this image, point out the tampering traces, and describe the target:"

    MAX_IMG_SIZE = 1024


# =================================================================
# 3. Utility classes and helper functions
# =================================================================
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff", ".webp"}


class TestDataset(Dataset):
    def __init__(self, image_dir: str, target_size: int = 1024):
        self.image_dir = image_dir
        self.target_size = target_size
        self.image_names = [
            f
            for f in os.listdir(image_dir)
            if os.path.splitext(f)[1].lower() in IMAGE_EXTENSIONS
        ]
        if not self.image_names:
            raise ValueError(f"No images found in {image_dir}!")

    def __len__(self):
        return len(self.image_names)

    def __getitem__(self, idx) -> Tuple[torch.Tensor, Tuple[int, int], str]:
        img_name = self.image_names[idx]
        img_path = os.path.join(self.image_dir, img_name)

        image = cv2.imread(img_path)
        if image is None:
            raise ValueError(f"Unable to read image: {img_path}")
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        orig_h, orig_w = image.shape[:2]
        image_resized = cv2.resize(
            image, (self.target_size, self.target_size), interpolation=cv2.INTER_LINEAR
        )

        image_tensor = torch.from_numpy(image_resized).float() / 255.0
        mean = torch.tensor([0.485, 0.456, 0.406]).view(1, 1, 3)
        std = torch.tensor([0.229, 0.224, 0.225]).view(1, 1, 3)
        image_tensor = (image_tensor - mean) / std
        image_tensor = image_tensor.permute(2, 0, 1)

        return image_tensor, (orig_h, orig_w), img_name


def get_ensemble_configs(weight_dir: str, full_weight: float) -> list:
    configs = []
    full_path = os.path.join(
        weight_dir, "training_full_data", "forensics_stage1_last.pth"
    )
    if not os.path.exists(full_path):
        raise FileNotFoundError(f"Full model not found: {full_path}")

    fold_paths = []
    fold_idx = 1
    while True:
        fold_path = os.path.join(
            weight_dir, f"training_kfold_{fold_idx}", "forensics_stage1_best.pth"
        )
        if os.path.exists(fold_path):
            fold_paths.append(fold_path)
            fold_idx += 1
        else:
            break

    if not fold_paths:
        raise FileNotFoundError(f"No kfold models found!")

    fold_weight = (1.0 - full_weight) / len(fold_paths)
    for fp in fold_paths:
        configs.append({"path": fp, "weight": fold_weight})
    configs.append({"path": full_path, "weight": full_weight})
    return configs


def mask_array_to_rle(mask: np.ndarray) -> str:
    binary_mask = (mask > 127).astype(np.uint8)
    mask_fortran = np.asfortranarray(binary_mask)
    rle_dict = mask_utils.encode(mask_fortran)
    if isinstance(rle_dict["counts"], bytes):
        rle_dict["counts"] = rle_dict["counts"].decode("utf-8")
    return json.dumps(rle_dict)


def prepare_image_and_bbox(image_path, rle_str, label):
    img = cv2.imread(image_path)
    if img is None:
        return None
    orig_h, orig_w = img.shape[:2]

    if label != 0 and pd.notna(rle_str) and rle_str != "":
        try:
            rle_dict = json.loads(rle_str)
            if isinstance(rle_dict["counts"], str):
                rle_dict["counts"] = rle_dict["counts"].encode("utf-8")
            mask = mask_utils.decode(rle_dict)
            binary_mask = (mask > 0).astype(np.uint8) * 255
            if cv2.countNonZero(binary_mask) > 0:
                x_b, y_b, w_b, h_b = cv2.boundingRect(binary_mask)
                cv2.rectangle(
                    img,
                    (x_b, y_b),
                    (x_b + w_b, y_b + h_b),
                    (0, 0, 255),
                    max(3, int(orig_w * 0.005)),
                )
        except Exception:
            pass

    if max(orig_h, orig_w) > CFG.MAX_IMG_SIZE:
        scale = CFG.MAX_IMG_SIZE / max(orig_h, orig_w)
        img = cv2.resize(
            img,
            (int(orig_w * scale), int(orig_h * scale)),
            interpolation=cv2.INTER_AREA,
        )

    return Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))


# =================================================================
# 4. Core pipeline stage definitions (in-memory handoff version)
# =================================================================
def run_stage1_sam(input_dir: str, mask_output_dir: str) -> pd.DataFrame:
    print("\n" + "=" * 50)
    print("Starting Stage 1: SAM model ensemble inference")
    print("=" * 50)

    device = torch.device(CFG.DEVICE)
    if device.type == "cuda":
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.backends.cudnn.allow_tf32 = True

    model_configs = get_ensemble_configs(CFG.WEIGHT_DIR, CFG.FULL_MODEL_WEIGHT)

    print("Loading base SAM backbone...")
    base_sam, _ = sam_model_registry[CFG.SAM_TYPE](
        image_size=CFG.IMAGE_SIZE, checkpoint=CFG.SAM_CHECKPOINT
    )
    model = ForensicsSAM(
        base_sam,
        r=8,
        forgery_experts_path=None,
        adversary_experts_path=None,
        load_pretrained=False,
        freeze_shared_experts=False,
        freeze_detector=False,
        enable_adversary_experts=False,
    ).to(device)

    dataset = TestDataset(image_dir=input_dir, target_size=CFG.IMAGE_SIZE)
    loader = DataLoader(
        dataset, batch_size=CFG.BATCH_SIZE, shuffle=False, num_workers=4
    )

    accumulated_results = {}

    with torch.no_grad():
        for config_idx, config in enumerate(model_configs, 1):
            weight_path, model_weight = config["path"], config["weight"]
            model.load_all_parameters(weight_path)
            model.eval()
            print(
                f"\n[{config_idx}/{len(model_configs)}] Inferring model: {os.path.basename(os.path.dirname(weight_path))} | weight: {model_weight:.4f}"
            )

            for images, (orig_hs, orig_ws), img_names in tqdm(
                loader, desc="Inference", leave=False
            ):
                images = images.to(device, non_blocking=True)
                activate_adv = torch.zeros(
                    images.size(0), device=device, dtype=torch.long
                )

                with torch.autocast(device_type="cuda", dtype=torch.float16):
                    mask_logits, cls_logits = model(images, activate_adv)

                cls_probs = torch.sigmoid(cls_logits.float()).cpu().numpy()
                mask_probs = torch.sigmoid(mask_logits.float()).cpu().half()

                for i in range(images.size(0)):
                    img_name = img_names[i]
                    if img_name not in accumulated_results:
                        accumulated_results[img_name] = {
                            "cls_prob": 0.0,
                            "mask_prob": torch.zeros_like(mask_probs[i]),
                            "orig_h": orig_hs[i].item(),
                            "orig_w": orig_ws[i].item(),
                        }
                    accumulated_results[img_name]["cls_prob"] += (
                        float(cls_probs[i][0]) * model_weight
                    )
                    accumulated_results[img_name]["mask_prob"] += (
                        mask_probs[i] * model_weight
                    )

    print(f"\nModel traversal complete! Generating preliminary inference logic...")
    logic_data_rows = []

    for img_name, data in tqdm(accumulated_results.items(), desc="Processing Results"):
        final_cls_prob = data["cls_prob"]
        pred_label = 1 if final_cls_prob > CFG.MANUAL_THRESHOLD else 0
        case_id = os.path.splitext(img_name)[0]

        mask_prob = data["mask_prob"].float().unsqueeze(0)
        orig_h, orig_w = data["orig_h"], data["orig_w"]

        mask_prob_resized = F.interpolate(
            mask_prob, size=(orig_h, orig_w), mode="bilinear", align_corners=False
        )[0, 0]

        mask_binary = (mask_prob_resized > CFG.MANUAL_THRESHOLD).byte().numpy() * 255
        mask_active_pixels = int(np.sum(mask_binary > 127))

        # Mask image saving is kept for inspection; comment out the next two lines if not needed
        mask_save_path = os.path.join(mask_output_dir, case_id + ".png")
        cv2.imwrite(mask_save_path, mask_binary)

        if pred_label == 0 or mask_active_pixels == 0:
            location = json.dumps({"size": [orig_h, orig_w], "counts": ""})
        else:
            location = mask_array_to_rle(mask_binary)

        logic_data_rows.append(
            {
                "image_name": img_name,
                "label": pred_label,
                "location": location,
                "explanation": "",
                "cls_prob": round(final_cls_prob, 6),
            }
        )

    # ================= VRAM reclamation core section =================
    print("Releasing SAM model VRAM...")
    del model
    del base_sam
    torch.cuda.empty_cache()
    gc.collect()
    # ==================================================================

    print("Stage 1 complete! Data now resides in memory.")
    return pd.DataFrame(logic_data_rows)


def run_stage2_llm(df: pd.DataFrame, input_dir: str) -> pd.DataFrame:
    print("\n" + "=" * 50)
    print("Starting Stage 2: vLLM multimodal verification and explanation generation")
    print("=" * 50)

    # Ensure VRAM is clean again
    torch.cuda.empty_cache()

    if "label" not in df.columns:
        df["label"] = (
            (df["cls_prob"] >= 0.5).astype(int) if "cls_prob" in df.columns else 0
        )

    print("Initializing vLLM engine...")
    processor = AutoProcessor.from_pretrained(
        CFG.LLM_MODEL_PATH, trust_remote_code=True, local_files_only=True
    )
    llm = LLM(
        model=CFG.LLM_MODEL_PATH,
        trust_remote_code=True,
        dtype="bfloat16",
        tensor_parallel_size=CFG.TENSOR_PARALLEL,
        max_model_len=CFG.MAX_MODEL_LEN,
        gpu_memory_utilization=0.9,
        enforce_eager=True,
        limit_mm_per_prompt={"image": 1},
    )

    # --- 1. Re-judge ambiguous data ---
    print(
        f"Looking for ambiguous samples with probability in {CFG.PROB_LOWER}~{CFG.PROB_UPPER}..."
    )
    uncertain_indices, uncertain_inputs = [], []
    for idx in df.index:
        cls_prob = float(df.loc[idx, "cls_prob"])
        if CFG.PROB_LOWER <= cls_prob <= CFG.PROB_UPPER:
            img_path = os.path.join(input_dir, df.loc[idx, "image_name"])
            pil_image = prepare_image_and_bbox(img_path, "", 0)
            if pil_image is None:
                continue

            messages = [
                {
                    "role": "user",
                    "content": [
                        {"type": "image"},
                        {"type": "text", "text": CFG.PROMPT_CLASSIFY},
                    ],
                }
            ]
            formatted_prompt = processor.apply_chat_template(
                messages, tokenize=False, add_generation_prompt=True
            )
            uncertain_inputs.append(
                {"prompt": formatted_prompt, "multi_modal_data": {"image": pil_image}}
            )
            uncertain_indices.append(idx)

    if uncertain_inputs:
        print(f"Starting real/fake classification ({len(uncertain_inputs)} items)...")
        sp_cls = SamplingParams(
            temperature=0.0,
            max_tokens=CFG.MAX_TOKENS,
            stop_token_ids=[processor.tokenizer.eos_token_id],
        )
        cls_outputs = llm.generate(
            uncertain_inputs, sampling_params=sp_cls, use_tqdm=True
        )

        for i, idx in enumerate(uncertain_indices):
            raw_ans = cls_outputs[i].outputs[0].text.strip()
            clean_ans = re.sub(r"(?is)<think>.*?(</think>|$)", "", raw_ans).strip()
            if "fake" in clean_ans.lower():
                df.loc[idx, "label"] = 1
            elif "real" in clean_ans.lower():
                df.loc[idx, "label"] = 0
            else:
                df.loc[idx, "label"] = 1 if float(df.loc[idx, "cls_prob"]) >= 0.5 else 0

    # --- 2. Batch generate final explanations ---
    print("Building the final explanation generation queue...")
    vllm_inputs, valid_indices = [], []
    for idx in df.index:
        img_path = os.path.join(input_dir, df.loc[idx, "image_name"])
        label = int(df.loc[idx, "label"])
        rle_str = df.loc[idx, "location"]

        pil_image = prepare_image_and_bbox(img_path, rle_str, label)
        if pil_image is None:
            continue

        selected_prompt = CFG.PROMPT_REAL if label == 0 else CFG.PROMPT_FAKE
        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "image"},
                    {"type": "text", "text": selected_prompt},
                ],
            }
        ]
        formatted_prompt = processor.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )

        vllm_inputs.append(
            {"prompt": formatted_prompt, "multi_modal_data": {"image": pil_image}}
        )
        valid_indices.append(idx)

    print(
        f"Starting batch generation of final explanations ({len(vllm_inputs)} items)..."
    )
    sp_final = SamplingParams(
        temperature=CFG.TEMPERATURE,
        max_tokens=CFG.MAX_TOKENS,
        stop_token_ids=[processor.tokenizer.eos_token_id],
    )
    outputs = llm.generate(vllm_inputs, sampling_params=sp_final, use_tqdm=True)

    df["explanation"] = ""
    for i, idx in enumerate(valid_indices):
        raw_text = outputs[i].outputs[0].text.strip()
        clean_text = re.sub(r"(?is)<think>.*?(</think>|$)", "", raw_text)
        clean_text = clean_text.replace("**", "").replace('"', '"')
        df.loc[idx, "explanation"] = re.sub(r"[\r\n\t]+", " ", clean_text).strip()

    # ================= VRAM reclamation core section =================
    print("Releasing vLLM model VRAM...")
    # Destroy vLLM distributed state (prevent leftovers)
    from vllm.distributed.parallel_state import destroy_model_parallel

    destroy_model_parallel()
    del llm
    del processor
    torch.cuda.empty_cache()
    gc.collect()
    # ==================================================================

    print(f"Stage 2 complete! Data explanations have been appended.")
    return df


def run_stage3_postprocess(df: pd.DataFrame, output_path: str):
    print("\n" + "=" * 50)
    print("Starting Stage 3: final format cleaning and packaging")
    print("=" * 50)

    def process_location(location_str):
        if pd.isna(location_str) or not location_str:
            return location_str
        try:
            location = json.loads(location_str)
            location["counts"] = ""  # Clear counts
            return json.dumps(location, ensure_ascii=False)
        except:
            return location_str

    df["location"] = df["location"].apply(process_location)
    result_df = df[["image_name", "label", "location", "explanation"]]

    # Ensure the output directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    result_df.to_csv(output_path, index=False, encoding="utf-8")
    print(
        f"All processing complete! The final submission file has been generated and saved to:\n-> {output_path}"
    )


# =================================================================
# 5. Entry point and command-line parsing
# =================================================================
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="End-to-end SAM + LLM image tampering analysis pipeline"
    )
    # Input and output are also dynamically assembled from PROJECT_ROOT
    parser.add_argument(
        "--input_path",
        type=str,
        default=os.path.join(PROJECT_ROOT, "data/ForgeryAnalysis_Stage_2_Test/Image"),
        help="Input dataset path (directory containing the test images)",
    )
    parser.add_argument(
        "--output_path",
        type=str,
        default=os.path.join(PROJECT_ROOT, "results_val/final_submission.csv"),
        help="CSV file path for the final inference results output",
    )
    args = parser.parse_args()

    # If needed, a separate folder can be specified for masks
    mask_output_dir = os.path.join(os.path.dirname(args.output_path), "masks")
    os.makedirs(mask_output_dir, exist_ok=True)

    print(f"Dataset input directory: {os.path.abspath(args.input_path)}")
    print(f"Final output file: {os.path.abspath(args.output_path)}")

    # ==================================
    # Pipeline data is passed directly in memory (df)
    # ==================================

    # Stage 1: obtain the initial inference DataFrame
    df_stage1 = run_stage1_sam(args.input_path, mask_output_dir)

    # Stage 2: pass in the DataFrame; vLLM performs multimodal verification and appends explanations
    df_stage2 = run_stage2_llm(df_stage1, args.input_path)

    # Stage 3: perform final cleaning on the DataFrame and write it out to the specified output_path
    run_stage3_postprocess(df_stage2, args.output_path)
